### ISSUE TITLE
Incorrect typehints for dg.add_int8 and add_uint8

### ISSUE THREAD

**Issue by Wizzerinus** [WMOkiishi/types-panda3d#14]
Version 0.3.3

These functions are declared with `value: str` instead of int right now I think

**Comment by WMOkiishi** [comment]
This is an interesting one... I've suspected something was wrong, because the type hints don't match the documentation. However, `interrogatedb` insists that the values in these methods should be strings. It's an easy fix, but I do wonder why they're typed as strings in the first place. Do you know why that might be?

**Comment by WMOkiishi** [comment]
Ok, I've figured out the issue. The Python bindings map `char` to `str`, but `signed char` and `unsigned char` to `int`. Their "atomic tokens", though, are both the same. I'll add a special case for these.
